const STATE_META: Record<ToothState, StateMeta> = {
  saudavel: {
    label: "Saudável",
    dot: "bg-muted",
    crown: "#fdfcf7",
    crownStroke: "#78716c",
    root: "#f3ead4",
    rootStroke: "#78716c",
  },
  carie: {
    label: "Cárie",
    dot: "bg-amber-500",
    crown: "#fde68a",
    crownStroke: "#92400e",
    root: "#f3ead4",
    rootStroke: "#78716c",
  },
  restauracao: {
    label: "Restauração",
    dot: "bg-blue-500",
    crown: "#bfdbfe",
    crownStroke: "#1e3a8a",
    root: "#f3ead4",
    rootStroke: "#78716c",
  },
  tratamento: {
    label: "Tratamento",
    dot: "bg-emerald-500",
    crown: "#a7f3d0",
    crownStroke: "#064e3b",
    root: "#f3ead4",
    rootStroke: "#78716c",
  },
  extracao: {
    label: "Extração",
    dot: "bg-red-500",
    crown: "#fecaca",
    crownStroke: "#7f1d1d",
    root: "#fecaca",
    rootStroke: "#7f1d1d",
  },
  ausente: {
    label: "Ausente",
    dot: "bg-muted-foreground",
    crown: "#e5e7eb",
    crownStroke: "#6b7280",
    root: "#e5e7eb",
    rootStroke: "#6b7280",
    opacity: 0.35,
  },
};
