/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedValidacoesRouteImport } from './routes/_authenticated/validacoes'
import { Route as AuthenticatedProntuariosRouteImport } from './routes/_authenticated/prontuarios'
import { Route as AuthenticatedPacientesRouteImport } from './routes/_authenticated/pacientes'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedProntuariosNovoRouteImport } from './routes/_authenticated/prontuarios.novo'
import { Route as AuthenticatedProntuariosProntuarioIdRouteImport } from './routes/_authenticated/prontuarios.$prontuarioId'
import { Route as AuthenticatedPacientesNovoRouteImport } from './routes/_authenticated/pacientes.novo'
import { Route as AuthenticatedPacientesPacienteIdRouteImport } from './routes/_authenticated/pacientes.$pacienteId'
import { Route as AuthenticatedAgendaNovoRouteImport } from './routes/_authenticated/agenda.novo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedValidacoesRoute = AuthenticatedValidacoesRouteImport.update({
  id: '/validacoes',
  path: '/validacoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProntuariosRoute =
  AuthenticatedProntuariosRouteImport.update({
    id: '/prontuarios',
    path: '/prontuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPacientesRoute = AuthenticatedPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProntuariosNovoRoute =
  AuthenticatedProntuariosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedProntuariosRoute,
  } as any)
const AuthenticatedProntuariosProntuarioIdRoute =
  AuthenticatedProntuariosProntuarioIdRouteImport.update({
    id: '/$prontuarioId',
    path: '/$prontuarioId',
    getParentRoute: () => AuthenticatedProntuariosRoute,
  } as any)
const AuthenticatedPacientesNovoRoute =
  AuthenticatedPacientesNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedPacientesRoute,
  } as any)
const AuthenticatedPacientesPacienteIdRoute =
  AuthenticatedPacientesPacienteIdRouteImport.update({
    id: '/$pacienteId',
    path: '/$pacienteId',
    getParentRoute: () => AuthenticatedPacientesRoute,
  } as any)
const AuthenticatedAgendaNovoRoute = AuthenticatedAgendaNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AuthenticatedAgendaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AuthenticatedAgendaRouteWithChildren
  '/inicio': typeof AuthenticatedInicioRoute
  '/pacientes': typeof AuthenticatedPacientesRouteWithChildren
  '/prontuarios': typeof AuthenticatedProntuariosRouteWithChildren
  '/validacoes': typeof AuthenticatedValidacoesRoute
  '/agenda/novo': typeof AuthenticatedAgendaNovoRoute
  '/pacientes/$pacienteId': typeof AuthenticatedPacientesPacienteIdRoute
  '/pacientes/novo': typeof AuthenticatedPacientesNovoRoute
  '/prontuarios/$prontuarioId': typeof AuthenticatedProntuariosProntuarioIdRoute
  '/prontuarios/novo': typeof AuthenticatedProntuariosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AuthenticatedAgendaRouteWithChildren
  '/inicio': typeof AuthenticatedInicioRoute
  '/pacientes': typeof AuthenticatedPacientesRouteWithChildren
  '/prontuarios': typeof AuthenticatedProntuariosRouteWithChildren
  '/validacoes': typeof AuthenticatedValidacoesRoute
  '/agenda/novo': typeof AuthenticatedAgendaNovoRoute
  '/pacientes/$pacienteId': typeof AuthenticatedPacientesPacienteIdRoute
  '/pacientes/novo': typeof AuthenticatedPacientesNovoRoute
  '/prontuarios/$prontuarioId': typeof AuthenticatedProntuariosProntuarioIdRoute
  '/prontuarios/novo': typeof AuthenticatedProntuariosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRouteWithChildren
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/pacientes': typeof AuthenticatedPacientesRouteWithChildren
  '/_authenticated/prontuarios': typeof AuthenticatedProntuariosRouteWithChildren
  '/_authenticated/validacoes': typeof AuthenticatedValidacoesRoute
  '/_authenticated/agenda/novo': typeof AuthenticatedAgendaNovoRoute
  '/_authenticated/pacientes/$pacienteId': typeof AuthenticatedPacientesPacienteIdRoute
  '/_authenticated/pacientes/novo': typeof AuthenticatedPacientesNovoRoute
  '/_authenticated/prontuarios/$prontuarioId': typeof AuthenticatedProntuariosProntuarioIdRoute
  '/_authenticated/prontuarios/novo': typeof AuthenticatedProntuariosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agenda'
    | '/inicio'
    | '/pacientes'
    | '/prontuarios'
    | '/validacoes'
    | '/agenda/novo'
    | '/pacientes/$pacienteId'
    | '/pacientes/novo'
    | '/prontuarios/$prontuarioId'
    | '/prontuarios/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agenda'
    | '/inicio'
    | '/pacientes'
    | '/prontuarios'
    | '/validacoes'
    | '/agenda/novo'
    | '/pacientes/$pacienteId'
    | '/pacientes/novo'
    | '/prontuarios/$prontuarioId'
    | '/prontuarios/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/agenda'
    | '/_authenticated/inicio'
    | '/_authenticated/pacientes'
    | '/_authenticated/prontuarios'
    | '/_authenticated/validacoes'
    | '/_authenticated/agenda/novo'
    | '/_authenticated/pacientes/$pacienteId'
    | '/_authenticated/pacientes/novo'
    | '/_authenticated/prontuarios/$prontuarioId'
    | '/_authenticated/prontuarios/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/validacoes': {
      id: '/_authenticated/validacoes'
      path: '/validacoes'
      fullPath: '/validacoes'
      preLoaderRoute: typeof AuthenticatedValidacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prontuarios': {
      id: '/_authenticated/prontuarios'
      path: '/prontuarios'
      fullPath: '/prontuarios'
      preLoaderRoute: typeof AuthenticatedProntuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pacientes': {
      id: '/_authenticated/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AuthenticatedPacientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prontuarios/novo': {
      id: '/_authenticated/prontuarios/novo'
      path: '/novo'
      fullPath: '/prontuarios/novo'
      preLoaderRoute: typeof AuthenticatedProntuariosNovoRouteImport
      parentRoute: typeof AuthenticatedProntuariosRoute
    }
    '/_authenticated/prontuarios/$prontuarioId': {
      id: '/_authenticated/prontuarios/$prontuarioId'
      path: '/$prontuarioId'
      fullPath: '/prontuarios/$prontuarioId'
      preLoaderRoute: typeof AuthenticatedProntuariosProntuarioIdRouteImport
      parentRoute: typeof AuthenticatedProntuariosRoute
    }
    '/_authenticated/pacientes/novo': {
      id: '/_authenticated/pacientes/novo'
      path: '/novo'
      fullPath: '/pacientes/novo'
      preLoaderRoute: typeof AuthenticatedPacientesNovoRouteImport
      parentRoute: typeof AuthenticatedPacientesRoute
    }
    '/_authenticated/pacientes/$pacienteId': {
      id: '/_authenticated/pacientes/$pacienteId'
      path: '/$pacienteId'
      fullPath: '/pacientes/$pacienteId'
      preLoaderRoute: typeof AuthenticatedPacientesPacienteIdRouteImport
      parentRoute: typeof AuthenticatedPacientesRoute
    }
    '/_authenticated/agenda/novo': {
      id: '/_authenticated/agenda/novo'
      path: '/novo'
      fullPath: '/agenda/novo'
      preLoaderRoute: typeof AuthenticatedAgendaNovoRouteImport
      parentRoute: typeof AuthenticatedAgendaRoute
    }
  }
}

interface AuthenticatedAgendaRouteChildren {
  AuthenticatedAgendaNovoRoute: typeof AuthenticatedAgendaNovoRoute
}

const AuthenticatedAgendaRouteChildren: AuthenticatedAgendaRouteChildren = {
  AuthenticatedAgendaNovoRoute: AuthenticatedAgendaNovoRoute,
}

const AuthenticatedAgendaRouteWithChildren =
  AuthenticatedAgendaRoute._addFileChildren(AuthenticatedAgendaRouteChildren)

interface AuthenticatedPacientesRouteChildren {
  AuthenticatedPacientesPacienteIdRoute: typeof AuthenticatedPacientesPacienteIdRoute
  AuthenticatedPacientesNovoRoute: typeof AuthenticatedPacientesNovoRoute
}

const AuthenticatedPacientesRouteChildren: AuthenticatedPacientesRouteChildren =
  {
    AuthenticatedPacientesPacienteIdRoute:
      AuthenticatedPacientesPacienteIdRoute,
    AuthenticatedPacientesNovoRoute: AuthenticatedPacientesNovoRoute,
  }

const AuthenticatedPacientesRouteWithChildren =
  AuthenticatedPacientesRoute._addFileChildren(
    AuthenticatedPacientesRouteChildren,
  )

interface AuthenticatedProntuariosRouteChildren {
  AuthenticatedProntuariosProntuarioIdRoute: typeof AuthenticatedProntuariosProntuarioIdRoute
  AuthenticatedProntuariosNovoRoute: typeof AuthenticatedProntuariosNovoRoute
}

const AuthenticatedProntuariosRouteChildren: AuthenticatedProntuariosRouteChildren =
  {
    AuthenticatedProntuariosProntuarioIdRoute:
      AuthenticatedProntuariosProntuarioIdRoute,
    AuthenticatedProntuariosNovoRoute: AuthenticatedProntuariosNovoRoute,
  }

const AuthenticatedProntuariosRouteWithChildren =
  AuthenticatedProntuariosRoute._addFileChildren(
    AuthenticatedProntuariosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRouteWithChildren
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedPacientesRoute: typeof AuthenticatedPacientesRouteWithChildren
  AuthenticatedProntuariosRoute: typeof AuthenticatedProntuariosRouteWithChildren
  AuthenticatedValidacoesRoute: typeof AuthenticatedValidacoesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRouteWithChildren,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedPacientesRoute: AuthenticatedPacientesRouteWithChildren,
  AuthenticatedProntuariosRoute: AuthenticatedProntuariosRouteWithChildren,
  AuthenticatedValidacoesRoute: AuthenticatedValidacoesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
